export const COLORS = {
  BACKGROUND: '#f2f2f7',
  ICON: '#d1d1d6',
  BUTTON: '#0000ff',
  TEXT_SECONDARY: '#c7c7cc',
  WHITE: '#ffffff',
  BLACK: '#000000',
};

export const mock = [
  {
    id: '1',
    name: 'Home',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '2',
    name: 'Food outside',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '3',
    name: 'Other',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '4',
    name: 'Activities',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '5',
    name: 'Meal',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '6',
    name: 'Shopping',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '7',
    name: 'Bills',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '8',
    name: 'Subscriptions',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '9',
    name: 'Cars',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '10',
    name: 'Pets',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '11',
    name: 'Health',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '12',
    name: 'Beauty',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
  {
    id: '13',
    name: 'Travel',
    expenses: 0,
    icon: '',
    color: COLORS.BLACK,
  },
];
